Header header

int64 lat
int64 lon
int64 best_lat
int64 best_lon

int64 hgt 
  
int64 sp_x
int64 sp_y
int64 best_sp_x
int64 best_sp_y
int64 best_sp_z
  
int64 heading_angle

int64 pitch_angle
int64 roll_angle
int64 yaw_angle
int64 pitch_anglevel
int64 roll_anglevel
int64 yaw_anglevel

int64 accx
int64 accy
int64 accz

uint8 motor1rpm
uint8 motor2rpm
uint8 motor3rpm
uint8 motor4rpm
uint8 motor5rpm
uint8 motor6rpm
